[FIX] l10n_it_edi: post invoice w/ multiple downpayments
Scenario:

- create a sale order and confirm it
- create two partial down payments for that sale order and confirm them
- create a invoice for the remaining amount and confirm it
- send and print the invoice (with Send to Tax Agency selected)

Result:

Traceback error is raised:

> ...
>   File "addons/account/models/account_tax.py", line 2475, in _dispatch_negative_lines
>     line.setdefault('discount_amount', line['discount_amount_before_dispatching'])
> KeyError: 'discount_amount_before_dispatching'

Why:

bbe04fb62916ae326c830e89b2664dfd32b62b75 was modifying the list
base_lines while looping over it, so we would not iterate over all
elements, for example:

> l = [5, 6, 7, 8]
> for i in l: print(i);l.remove(i)

shows 5 and 7

Notes:

Without the fix, the added test fails with the error given above.

The same code is in 17.0 but doesn't cause this error because we have
two loops. One that sets 'discount_amount_before_dispatching' and after
that one that remove downpayment from base_lines. But the fix should
still be backported because it works by chance.

opw-4496310

closes odoo/odoo#194949

Signed-off-by: John Laterre (jol) <jol@odoo.com>